export const FAVORITES_PROCESSING_START = 'FAVORITES_PROCESSING_START'
export const FAVORITES_PROCESSING_END = 'FAVORITES_PROCESSING_END'
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS'
export const SET_TIMEOUT_ID = 'SET_TIMEOUT_ID'
