export const AUTH_DETERMINED = 'app/AUTH_DETERMINED'

export const SET_MEDIA_BREAKPOINTS = 'app/SET_MEDIA_BREAKPOINTS'

export const SET_VISIBLE_SUCCESS_MESSAGE = 'app/SET_VISIBLE_SUCCESS_MESSAGE'

export const INIT_APP = '@@INIT'
