export const API_FUNCTION_ARN = 'apiFunctionArn'
export const API_LONG_TASK_FUNCTION_ARN = 'apiLongTaskFunctionArn'
export const API_DYNAMO_TABLE_NAME = 'apiDynamoTableName'
export const API_CLOUDWATCH_EVENTS_IAM_ROLE = 'apiCloudWatchEventsIamRole'
export const API_CLOUDWATCH_EVENTS_RULE_ARN = 'apiCloudWatchEventsIamRule'
export const API_LAMBDA_EXECUTION_ROLE_ARN = 'apiLambdaExecutionRoleArn'
