export const API_FUNCTION_ARN = 'apiFunctionArn'
export const API_LONG_TASK_FUNCTION_ARN = 'apiLongTaskFunctionArn'
export const API_LAMBDA_CLOUDWATCH_FUNCTION_ARN = 'apiCloudwatchFunctionArn'
export const API_DYNAMO_TABLE_NAME = 'apiDynamoTableName'
export const PERFORMANCE_TEST_DYNAMODB_DATA_TABLE_ARN = 'performanceTestDynamoDBDataTableArn'
