export const CREATE_PROJECT = 'CREATE_PROJECT'
export const GET_PROJECT = 'GET_PROJECT'
export const SAVE_PARTIAL_DARE_FORM = 'SAVE_PARTIAL_DARE_FORM'
export const CLEAR_PARTIAL_FORM_KEYS = 'CLEAR_PARTIAL_FORM_KEYS'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const REJECT_ACTIVE_PROJECT = 'REJECT_ACTIVE_PROJECT'
export const REVIEW_DELIVERY = 'REVIEW_DELIVERY'

export const GET_PROJECT_ADMIN = 'GET_PROJECT_ADMIN'

export const ACCEPT_PROJECT = 'ACCEPT_PROJECT'
export const REJECT_PROJECT = 'REJECT_PROJECT'

export const PLEDGE_PROJECT = 'PLEDGE_PROJECT'
export const GET_PLEDGED_PROJECTS = 'GET_PLEDGED_PROJECTS'

export const AUDIT_FAVORITES = 'AUDIT_FAVORITES'

export const AUDIT_PROJECT = 'AUDIT_PROJECT'

export const GET_ACTIVE_PROJECTS = 'GET_ACTIVE_PROJECTS'
export const GET_PENDING_PROJECTS = 'GET_PENDING_PROJECTS'
export const GET_FAVORITES_LIST = 'GET_FAVORITES_LIST'
export const GET_MY_PROJECTS = 'GET_MY_PROJECTS'
export const GET_PENDING_DELIVERIES = 'GET_PENDING_DELIVERIES'

export const GET_USERS_TWITCH = 'GET_USERS_TWITCH'
export const GET_OAUTH_TOKENS = 'GET_OAUTH_TOKENS'
export const ADD_OAUTH_TOKEN = 'ADD_OAUTH_TOKEN'
export const AUTH_TWITCH = 'AUTH_TWITCH'

export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD'
export const GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD'
export const DELETE_PAYMENT_METHOD = 'DELETE_PAYMENT_METHOD'
export const GET_PAYMENT_METHODS = 'GET_PAYMENT_METHODS'
export const SET_DEFAULT_PAYMENT_METHOD = 'SET_DEFAULT_PAYMENT_METHOD'

export const DELIVERY_DARE_INIT = 'DELIVERY_DARE_INIT'
export const DELIVERY_DARE = 'DELIVERY_DARE'
export const GET_ACCEPTED_PROJECTS = 'GET_ACCEPTED_PROJECTS'

export const ADD_PAYOUT_METHOD = 'ADD_PAYOUT_METHOD'
export const GET_PAYOUT_METHOD = 'GET_PAYOUT_METHOD'
export const UPDATE_PAYOUT_METHOD = 'UPDATE_PAYOUT_METHOD'

export const CAPTURE_PROJECT_PAYMENTS = 'CAPTURE_PROJECT_PAYMENTS'
export const PAYOUT_ASSIGNEES = 'PAYOUT_ASSIGNEES'
export const PAY_OUTSTANDING_PAYOUTS = 'PAY_OUTSTANDING_PAYOUTS'

export const CLEAR_PROJECT_RECORDS = 'CLEAR_PROJECT_RECORDS'
export const COPY_DB_RECORDS = 'COPY_DB_RECORDS'
